language: python
sudo: false

python:
  - '3.4'
  - '3.5'

env:
  - TOXENV=py34
  - TOXENV=py35

matrix:
  exclude:
  - python: '3.4'
    env: TOXENV=py35
  - python: '3.5'
    env: TOXENV=py34

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coverage coveralls
  - coverage report
  - coveralls
